# Generated by Django 2.2.5 on 2022-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191023_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
